### ISSUE TITLE
SuperColliderActivity crash when phone orientation switches to landscape

### ISSUE THREAD

**Issue by danstowell** [glastonbridge/SuperCollider-Android#11]
When I tilt my HTC Tattoo and the orientation switches to landscape, the SuperColliderActivity crashes. It seems the hardware audio input goes into standby briefly...

In the following backtrace, the exception (fail to call super) is easily fixable but the user-facing problem will be the same - die on tilt.

D/StatusBar(   81): updateResources
D/StatusBar(   81): updateExpandedViewPos before pos=-10000 mTrackingParams.y=-278 mTrackingPosition=-278
D/StatusBar(   81): performAddUpdateIcon icon=IconData(slot='clock' text='7:07 PM') notification=null key=android.os.Binder@436f8140
I/AudioHardwareMSM72XX(   57): AudioHardware PCM record is going to standby.
I/AudioHardwareMSM72XX(   57): closeInputStream. in->format()=1
I/ActivityManager(   81): Stopping service: uk.co.mcld.dabble.GlastoCollider1/.ScService
D/AndroidRuntime(  763): Shutting down VM
W/dalvikvm(  763): threadid=3: thread exiting with uncaught exception (group=0x4001db88)
E/AndroidRuntime(  763): Uncaught handler: thread main exiting due to uncaught exception
E/AndroidRuntime(  763): android.app.SuperNotCalledException: Activity {uk.co.mcld.dabble.GlastoCollider1/uk.co.mcld.dabble.GlastoCollider1.SuperColli
derActivity} did not call through to super.onDestroy()
E/AndroidRuntime(  763):        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3466)
E/AndroidRuntime(  763):        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3495)
E/AndroidRuntime(  763):        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3589)
E/AndroidRuntime(  763):        at android.app.ActivityThread.access$2200(ActivityThread.java:123)
E/AndroidRuntime(  763):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
E/AndroidRuntime(  763):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  763):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(  763):        at android.app.ActivityThread.main(ActivityThread.java:4321)
E/AndroidRuntime(  763):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  763):        at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(  763):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime(  763):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
E/AndroidRuntime(  763):        at dalvik.system.NativeStart.main(Native Method)
I/Process (   81): Sending signal. PID: 763 SIG: 3
I/dalvikvm(  763): threadid=7: reacting to signal 3
I/dalvikvm(  763): Wrote stack trace to '/data/anr/traces.txt'

**Comment by danstowell** [comment]
Fixed in commit glastonbridge/SuperCollider-Android@2c9e4d4 - if you add a property to the XML to tell android we'll handle orientation changes ourselves, then tipping the screen no longer interrupts the audio significantly.
